use smash::app::sv_animcmd::*;
use smash::phx::Hash40;

use smash::app::lua_bind::{AttackModule, HitModule, WorkModule};
use smash::app::*;
use smash::lib::lua_const::*;
use smash::lua2cpp::*;
use smash_script::*;
use smashline::*;
use std::arch::asm;

#[acmd_script(
    agent = "donkey",
    script =  "game_specialhi",
    category = ACMD_GAME)]
unsafe fn dk_upb(fighter: &mut L2CAgentBase) {
    let lua_state = fighter.lua_state_agent;
    frame(lua_state, 5.0);
    if macros::is_excute(fighter) {
        damage!(
            fighter,
            *MA_MSC_DAMAGE_DAMAGE_NO_REACTION,
            *DAMAGE_NO_REACTION_MODE_ALWAYS,
            0
        );
    }
    frame(lua_state, 18.0);
    if macros::is_excute(fighter) {
        damage!(
            fighter,
            *MA_MSC_DAMAGE_DAMAGE_NO_REACTION,
            *DAMAGE_NO_REACTION_MODE_NORMAL,
            0
        );
    }
    frame(lua_state, 19.0);
    if macros::is_excute(fighter) {
        macros::HIT_NODE(fighter, Hash40::new("armr"), *HIT_STATUS_XLU);
        macros::ATTACK(
            fighter,
            /*ID*/ 0,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("armr"),
            /*Damage*/ 5.0,
            /*Angle*/ 95,
            /*KBG*/ 90,
            /*FKB*/ 30,
            /*BKB*/ 0,
            /*Size*/ 6.0,
            /*X*/ 6.5,
            /*Y*/ -1.0,
            /*Z*/ -1.0,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 1.0,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_POS,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 1,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_G,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_L,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 1,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("armr"),
            /*Damage*/ 5.0,
            /*Angle*/ 80,
            /*KBG*/ 90,
            /*FKB*/ 30,
            /*BKB*/ 0,
            /*Size*/ 5.0,
            /*X*/ 0.0,
            /*Y*/ -1.0,
            /*Z*/ -1.0,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 1.0,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_POS,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 1,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_G,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_L,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 2,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("shoulderr"),
            /*Damage*/ 5.0,
            /*Angle*/ 80,
            /*KBG*/ 90,
            /*FKB*/ 30,
            /*BKB*/ 0,
            /*Size*/ 4.0,
            /*X*/ 0.0,
            /*Y*/ 0.0,
            /*Z*/ 0.0,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 1.0,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_POS,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 1,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_G,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_L,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 3,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("armr"),
            /*Damage*/ 5.0,
            /*Angle*/ 366,
            /*KBG*/ 90,
            /*FKB*/ 30,
            /*BKB*/ 0,
            /*Size*/ 6.0,
            /*X*/ 6.5,
            /*Y*/ -1.0,
            /*Z*/ -1.0,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 1.0,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_POS,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 1,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_A,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_L,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 4,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("armr"),
            /*Damage*/ 5.0,
            /*Angle*/ 366,
            /*KBG*/ 90,
            /*FKB*/ 30,
            /*BKB*/ 0,
            /*Size*/ 5.0,
            /*X*/ 0.0,
            /*Y*/ -1.0,
            /*Z*/ -1.0,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 1.0,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_POS,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 1,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_A,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_L,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 5,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("shoulderr"),
            /*Damage*/ 5.0,
            /*Angle*/ 366,
            /*KBG*/ 90,
            /*FKB*/ 30,
            /*BKB*/ 0,
            /*Size*/ 4.0,
            /*X*/ 0.0,
            /*Y*/ 0.0,
            /*Z*/ 0.0,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 1.0,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_POS,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 1,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_A,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_L,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
    }
    wait(lua_state, 1.0);
    if macros::is_excute(fighter) {
        AttackModule::clear_all(fighter.module_accessor);
    }
    frame(lua_state, 25.0);
    if macros::is_excute(fighter) {
        HitModule::set_status_all(fighter.module_accessor, HitStatus(*HIT_STATUS_NORMAL), 0);
        macros::ATTACK(
            fighter,
            /*ID*/ 0,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 1.4,
            /*Angle*/ 367,
            /*KBG*/ 55,
            /*FKB*/ 90,
            /*BKB*/ 0,
            /*Size*/ 4.0,
            /*X*/ 0.0,
            /*Y*/ 7.0,
            /*Z*/ 25.0,
            /*X2*/ Some(0.0),
            /*Y2*/ Some(12.0),
            /*Z2*/ Some(25.0),
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_F,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 1,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 1.4,
            /*Angle*/ 20,
            /*KBG*/ 100,
            /*FKB*/ 65,
            /*BKB*/ 0,
            /*Size*/ 5.0,
            /*X*/ 0.0,
            /*Y*/ 12.0,
            /*Z*/ 12.5,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_F,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 2,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 3.5,
            /*Angle*/ 60,
            /*KBG*/ 100,
            /*FKB*/ 0,
            /*BKB*/ 35,
            /*Size*/ 5.7,
            /*X*/ 0.0,
            /*Y*/ 13.5,
            /*Z*/ -2.5,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_B,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
    }
    wait(lua_state, 3.0);
    if macros::is_excute(fighter) {
        AttackModule::clear_all(fighter.module_accessor);
    }
    frame(lua_state, 32.0);
    if macros::is_excute(fighter) {
        macros::ATTACK(
            fighter,
            /*ID*/ 0,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 1.4,
            /*Angle*/ 367,
            /*KBG*/ 55,
            /*FKB*/ 80,
            /*BKB*/ 0,
            /*Size*/ 4.0,
            /*X*/ 0.0,
            /*Y*/ 7.0,
            /*Z*/ 25.0,
            /*X2*/ Some(0.0),
            /*Y2*/ Some(12.0),
            /*Z2*/ Some(25.0),
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_F,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 1,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 1.4,
            /*Angle*/ 20,
            /*KBG*/ 100,
            /*FKB*/ 65,
            /*BKB*/ 0,
            /*Size*/ 5.0,
            /*X*/ 0.0,
            /*Y*/ 12.0,
            /*Z*/ 12.5,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_F,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 2,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 3.5,
            /*Angle*/ 60,
            /*KBG*/ 100,
            /*FKB*/ 0,
            /*BKB*/ 35,
            /*Size*/ 5.7,
            /*X*/ 0.0,
            /*Y*/ 13.5,
            /*Z*/ -2.5,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_B,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
    }
    wait(lua_state, 2.0);
    if macros::is_excute(fighter) {
        AttackModule::clear_all(fighter.module_accessor);
    }
    frame(lua_state, 40.0);
    if macros::is_excute(fighter) {
        macros::ATTACK(
            fighter,
            /*ID*/ 0,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 1.4,
            /*Angle*/ 367,
            /*KBG*/ 55,
            /*FKB*/ 90,
            /*BKB*/ 0,
            /*Size*/ 4.0,
            /*X*/ 0.0,
            /*Y*/ 7.0,
            /*Z*/ 25.0,
            /*X2*/ Some(0.0),
            /*Y2*/ Some(12.0),
            /*Z2*/ Some(25.0),
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_F,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 1,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 1.4,
            /*Angle*/ 20,
            /*KBG*/ 100,
            /*FKB*/ 65,
            /*BKB*/ 0,
            /*Size*/ 5.0,
            /*X*/ 0.0,
            /*Y*/ 12.0,
            /*Z*/ 12.5,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_F,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 2,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 3.5,
            /*Angle*/ 60,
            /*KBG*/ 100,
            /*FKB*/ 0,
            /*BKB*/ 35,
            /*Size*/ 5.7,
            /*X*/ 0.0,
            /*Y*/ 13.5,
            /*Z*/ -2.5,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_B,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
    }
    wait(lua_state, 3.0);
    if macros::is_excute(fighter) {
        AttackModule::clear_all(fighter.module_accessor);
    }
    frame(lua_state, 49.0);
    if macros::is_excute(fighter) {
        macros::ATTACK(
            fighter,
            /*ID*/ 0,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 1.4,
            /*Angle*/ 367,
            /*KBG*/ 55,
            /*FKB*/ 90,
            /*BKB*/ 0,
            /*Size*/ 4.0,
            /*X*/ 0.0,
            /*Y*/ 7.0,
            /*Z*/ 25.0,
            /*X2*/ Some(0.0),
            /*Y2*/ Some(12.0),
            /*Z2*/ Some(25.0),
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_F,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 1,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 1.4,
            /*Angle*/ 20,
            /*KBG*/ 100,
            /*FKB*/ 65,
            /*BKB*/ 0,
            /*Size*/ 5.0,
            /*X*/ 0.0,
            /*Y*/ 12.0,
            /*Z*/ 12.5,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_F,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 2,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 3.5,
            /*Angle*/ 60,
            /*KBG*/ 100,
            /*FKB*/ 0,
            /*BKB*/ 35,
            /*Size*/ 5.7,
            /*X*/ 0.0,
            /*Y*/ 13.5,
            /*Z*/ -2.5,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_B,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
    }
    wait(lua_state, 2.0);
    if macros::is_excute(fighter) {
        AttackModule::clear_all(fighter.module_accessor);
    }
    frame(lua_state, 55.0);
    if macros::is_excute(fighter) {
        macros::ATTACK(
            fighter,
            /*ID*/ 0,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 1.4,
            /*Angle*/ 367,
            /*KBG*/ 55,
            /*FKB*/ 90,
            /*BKB*/ 0,
            /*Size*/ 4.0,
            /*X*/ 0.0,
            /*Y*/ 7.0,
            /*Z*/ 25.0,
            /*X2*/ Some(0.0),
            /*Y2*/ Some(12.0),
            /*Z2*/ Some(25.0),
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_F,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 1,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 1.4,
            /*Angle*/ 20,
            /*KBG*/ 100,
            /*FKB*/ 65,
            /*BKB*/ 0,
            /*Size*/ 5.0,
            /*X*/ 0.0,
            /*Y*/ 12.0,
            /*Z*/ 12.5,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_F,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 2,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 3.5,
            /*Angle*/ 60,
            /*KBG*/ 100,
            /*FKB*/ 0,
            /*BKB*/ 35,
            /*Size*/ 5.7,
            /*X*/ 0.0,
            /*Y*/ 13.5,
            /*Z*/ -2.5,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 0.8,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_B,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_rush"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_S,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
    }
    wait(lua_state, 4.0);
    if macros::is_excute(fighter) {
        AttackModule::clear_all(fighter.module_accessor);
    }
    frame(lua_state, 62.0);
    if macros::is_excute(fighter) {
        WorkModule::on_flag(
            fighter.module_accessor,
            /*Flag*/ *FIGHTER_DONKEY_STATUS_SPECIAL_HI_FLAG_YACL_DEFAULT,
        );
        WorkModule::on_flag(
            fighter.module_accessor,
            /*Flag*/ *FIGHTER_DONKEY_STATUS_SPECIAL_HI_FLAG_GROUND_SPINEND,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 0,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("top"),
            /*Damage*/ 8.0,
            /*Angle*/ 361,
            /*KBG*/ 120,
            /*FKB*/ 0,
            /*BKB*/ 60,
            /*Size*/ 8.0,
            /*X*/ 0.0,
            /*Y*/ 11.0,
            /*Z*/ 20.0,
            /*X2*/ Some(0.0),
            /*Y2*/ Some(11.0),
            /*Z2*/ Some(-4.0),
            /*Hitlag*/ 2.0,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_POS,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 0.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_normal"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_L,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_BODY,
        );
    }
    wait(lua_state, 1.0);
    if macros::is_excute(fighter) {
        AttackModule::clear_all(fighter.module_accessor);
    }
}

#[acmd_script(
    agent = "donkey",
    script =  "game_attacklw3",
    category = ACMD_GAME)]
unsafe fn dk_dtilt(fighter: &mut L2CAgentBase) {
    let lua_state = fighter.lua_state_agent;
    frame(lua_state, 5.0);
    if macros::is_excute(fighter) {
        macros::HIT_NODE(fighter, Hash40::new("arml"), *HIT_STATUS_XLU);
        macros::HIT_NODE(fighter, Hash40::new("shoulderl"), *HIT_STATUS_XLU);
    }
    frame(lua_state, 6.0);
    if macros::is_excute(fighter) {
        macros::ATTACK(
            fighter,
            /*ID*/ 0,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("shoulderl"),
            /*Damage*/ 6.0,
            /*Angle*/ 361,
            /*KBG*/ 100,
            /*FKB*/ 0,
            /*BKB*/ 20,
            /*Size*/ 4.4,
            /*X*/ 2.3,
            /*Y*/ 0.0,
            /*Z*/ 0.0,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 1.0,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_POS,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 50.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_normal"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_M,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_PUNCH,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 1,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("arml"),
            /*Damage*/ 6.0,
            /*Angle*/ 361,
            /*KBG*/ 100,
            /*FKB*/ 0,
            /*BKB*/ 20,
            /*Size*/ 4.4,
            /*X*/ 1.0,
            /*Y*/ 0.0,
            /*Z*/ 0.0,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 1.0,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_POS,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 50.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_normal"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_M,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_PUNCH,
        );
        macros::ATTACK(
            fighter,
            /*ID*/ 2,
            /*Part*/ 0,
            /*Bone*/ Hash40::new("arml"),
            /*Damage*/ 6.0,
            /*Angle*/ 361,
            /*KBG*/ 100,
            /*FKB*/ 0,
            /*BKB*/ 20,
            /*Size*/ 5.5,
            /*X*/ 8.5,
            /*Y*/ 0.0,
            /*Z*/ 0.0,
            /*X2*/ None,
            /*Y2*/ None,
            /*Z2*/ None,
            /*Hitlag*/ 1.0,
            /*SDI*/ 1.0,
            /*Clang_Rebound*/ *ATTACK_SETOFF_KIND_ON,
            /*FacingRestrict*/ *ATTACK_LR_CHECK_POS,
            /*SetWeight*/ false,
            /*ShieldDamage*/ 0,
            /*Trip*/ 50.0,
            /*Rehit*/ 0,
            /*Reflectable*/ false,
            /*Absorbable*/ false,
            /*Flinchless*/ false,
            /*DisableHitlag*/ false,
            /*Direct_Hitbox*/ true,
            /*Ground_or_Air*/ *COLLISION_SITUATION_MASK_GA,
            /*Hitbits*/ *COLLISION_CATEGORY_MASK_ALL,
            /*CollisionPart*/ *COLLISION_PART_MASK_ALL,
            /*FriendlyFire*/ false,
            /*Effect*/ Hash40::new("collision_attr_normal"),
            /*SFXLevel*/ *ATTACK_SOUND_LEVEL_M,
            /*SFXType*/ *COLLISION_SOUND_ATTR_PUNCH,
            /*Type*/ *ATTACK_REGION_PUNCH,
        );
        AttackModule::set_attack_height_all(
            fighter.module_accessor,
            smash::app::AttackHeight(*ATTACK_HEIGHT_LOW),
            false,
        );
    }
    frame(lua_state, 8.0);
    if macros::is_excute(fighter) {
        AttackModule::clear_all(fighter.module_accessor);
        HitModule::set_status_all(fighter.module_accessor, HitStatus(*HIT_STATUS_NORMAL), 0);
    }
}

pub fn install() {
    smashline::install_acmd_scripts!(dk_upb, dk_dtilt);
}
